import os.path

VERSION = "1.7.2"
MAIN_VERSION = ""
SUB_VERSION = ""
CODENAME = " (BETA)"
VER = VERSION + CODENAME
BDATE = ""
MAINVER = VERSION + CODENAME
BUILD_USERNAME = "rovertdude"
AUDIO_CACHE_PATH = os.path.join(os.getcwd(), "audio_cache")
DISCORD_MSG_CHAR_LIMIT = 2000
